
-- Handle all the network strings here

util.AddNetworkString( "hlmd_setviewtarget" )
util.AddNetworkString( "hlmd_setmodelcolor" )
util.AddNetworkString( "hlmd_setviewdistance" )
util.AddNetworkString( "hlmd_logevent" )
util.AddNetworkString( "hlmd_addteammember" )
util.AddNetworkString( "hlmd_removeteammember" )
util.AddNetworkString( "hlmd_clearteambars" )
util.AddNetworkString( "hlmd_clearinvalidteammates" )
util.AddNetworkString( "hlmd_ragdollhlmdnpc" )
util.AddNetworkString( "hlmd_removedeathragdoll" )
util.AddNetworkString( "hlmd_ragdollclean" )
util.AddNetworkString( "hlmd_addtextbubble" )
util.AddNetworkString( "hlmd_addtextbar" )
util.AddNetworkString( "hlmd_displaymainmenu" )
util.AddNetworkString( "hlmd_addhudindicator" )
util.AddNetworkString( "hlmd_mainmenuexit" )
util.AddNetworkString( "hlmd_controlmusic" )
util.AddNetworkString( "hlmd_mainmenuopened" )
util.AddNetworkString( "hlmd_freecamfovchange" )
util.AddNetworkString( "hlmd_sendfreecam" )
util.AddNetworkString( "hlmd_startfreecam" )